### ISSUE TITLE
新手求助 git bash 中遇到的问题

### ISSUE THREAD

**Issue by Zegendary** [felixonmars/ydcv#27]
你好
```
python ydcv.py apple
appleTraceback (most recent call last):
  File "ydcv.py", line 217, in <module>
    lookup_word(word)
  File "ydcv.py", line 177, in lookup_word
    print_explanation(json.loads(data), options)
  File "ydcv.py", line 104, in print_explanation
    print(" UK: [{0}]".format(_c(_b['uk-phonetic'], 'yellow')), end=',')
UnicodeEncodeError: 'gbk' codec can't encode character '\xe6' in position 7: illegal multibyte sequence
```
是哪里出了问题

**Comment by felixonmars** [comment]
看起来是因为国际音标不能用 gbk 编码输出。

**Comment by Zegendary** [comment]
谢谢 修改bug

**Comment by Zegendary** [comment]
谢谢修改bug，但仍有如下问题：附截图一张http://a2.qpic.cn/psb?/34a72754-a4bd-42dd-98a8-232f7c9643b3/alB1cSc6XIcqVP2.h1ALX.kGKu5T7xIfu3zVwFqIkhE!/c/dHEBAAAAAAAA&ek=1&kp=1&pt=0&bo=UwJJAVMCSQEFACM!&t=5&sce=0-12-12&rf=0-18
是我的gitbash的问题吗？

**Comment by pentie** [comment]
试了一下，这是git bash的环境变量问题，似乎很难在代码里面比较优雅的解决，git bash在中文版windows里面的中文乱码问题是由来已久，但是可以通过添加git bash的环境变量设置，在你的git bash里面执行以下代码：

```bash
cat >> ~/.bashrc << EOF
export PYTHONIOENCODING=UTF-8
EOF
```
然后重新打开一个gitbash，ydcv就正常了：
```
Pre--a-Laptop MINGW64 /f/Projects/ydcv (master)
$ ./ydcv.py apple
apple UK: ['æp(ə)l], US: ['æpl]
  Word Explanation:
     * n. 苹果，苹果树，苹果似的东西；[美俚]炸弹，手榴弹，（棒球的）球；[美俚]人，家伙。

  Web Reference:
     * Apple
       苹果; 苹果; 苹果公司
     * Apple Lossless
       Apple Lossless; 애플 무손실; Apple Lossless
     * Apple Store
       苹果商店; 苹果零售店; 苹果商店

  Online Resource:
     * http://www.ldoceonline.com/search/?q=apple

```

**Comment by Zegendary** [comment]
谢谢你的回复，通过你的方法问题已经解决！再次感谢
