### ISSUE TITLE
报告一个bug KeyError

### ISSUE THREAD

**Issue by hxse** [felixonmars/ydcv#56]
```
$ ydcv 
Traceback (most recent call last):
  File "/usr/bin/ydcv", line 11, in <module>
    load_entry_point('ydcv==0.7', 'console_scripts', 'ydcv')()
  File "/usr/lib/python3.7/site-packages/ydcv.py", line 353, in main
    sec = config["YDCV"]
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'YDCV'
```
环境:
4.19.34-1-MANJARO
ydcv 0.7-1

**Comment by hxse** [comment]
昨天还好好的, 今天系统更新之后出了这 bug ,请问, 原因大概是什么

**Comment by boypt** [comment]
请仔细阅读项目主页注意事项。

无弦 <notifications@github.com> 于 2019年4月29日周一 19:16写道：

**Comment by boypt** [comment]
fixed by #54
