### ISSUE TITLE
[bug] KeyError

### ISSUE THREAD

**Issue by Freed-Wu** [felixonmars/ydcv#59]
```
$ sudo pacman -S ydcv
$ ydcv
Traceback (most recent call last):
  File "/usr/bin/ydcv", line 33, in <module>
    sys.exit(load_entry_point('ydcv==0.7', 'console_scripts', 'ydcv')())
  File "/usr/lib/python3.10/site-packages/ydcv.py", line 353, in main
    sec = config["YDCV"]
  File "/usr/lib/python3.10/configparser.py", line 964, in __getitem__
    raise KeyError(key)
KeyError: 'YDCV'
```

**Comment by Freed-Wu** [comment]
<https://github.com/felixonmars/ydcv#%E6%B3%A8%E6%84%8F> I suggest to add a prompt on adding API-key.

**Comment by Freed-Wu** [comment]
Oh, it should be because the ydcv installed by pacman is older than the latest ydcv.
